### PR TITLE
Fix follow and unfollow user

### PR DESCRIPTION
**Pull request by CodyGramlich**
Fixes issue #553.

### CODE REVIEW

**Comment by j-rewerts** [comment]
@CodyGramlich Could you write some tests that verify the original problem and show how your changes resolve them?
Nice catch though. Surprised this wasn't reported before.

**Comment by CodyGramlich** [comment]
@j-rewerts Sure, I'll make a test by requesting to follow a user, and then requesting to get the user's that I'm following. Then I'll check if the user I tried to follow is in that list. There isn't really an easier way to test it because the response of following yourself is the same response as if you successfully followed someone else.

**Comment by CodyGramlich** [comment]
@j-rewerts I added some tests. One of them is to try to follow yourself and show that you're not one of your followers. The previous test does the same thing but for a different user and it shows that you are now following the user.

**Comment by j-rewerts** [comment]
Sorry for the delay @CodyGramlich. Could you resolve the conflicts?

**Comment by j-rewerts** [comment]
Thanks for the extensive tests! I'm trying out a new review process, so bear with me here.

**Pull request merged**
