### PR TITLE
Add support for https://developer.github.com/v3/pulls/#list-commits-on-a-pull-request

### PR DESCRIPTION
**Pull request by vicatcu**

### CODE REVIEW

**Comment by vicatcu** [comment]
Hi GitHub team, have the travis-ci checks failed because of something I did wrong? Seemed like a very straightforward change to me, but I'd be happy to be set straight.

**Comment by j-rewerts** [comment]
Hey @vicatcu! Thanks for the PR! We're getting the following in `repository.js`:

```
130:26  error  Missing JSDoc comment                         require-jsdoc
131:5   error  Expected indentation of 6 spaces but found 4  indent
```

In addition, please write an integration test for your new functionality. Thanks!

**Comment by vicatcu** [comment]
@j-rewerts cool, thanks for the clarification. I think I've incorporated the required changes to fix those problems. Since the change I've made is trivially derived based on the listPullRequestFiles implementation, and that doesn't seem to have any test to go with it, may I respectfully ask for exemption from writing a test? Travis-ci now seems to be failing for reasons unrelated to the changes I made, unless I'm mistaken?.

**Comment by j-rewerts** [comment]
Thanks @vicatcu! 

On the testing side, we use these tests to verify GitHub's API changes are picked up right away in our world. If you don't mind, I'd like to get a test in for this. If this feels a little outside your comfort zone, we may be able to get one of our community volunteers to work with you on this?

@CodyGramlich, @kylejeske any interest in helping write a test for this PR?

**Comment by jamesmortensen** [comment]
@j-rewerts this is implemented in #599 as of November 2019.  Is it possible to please merge that change in and release it.  I have been hacking the module manually pasting the changes in, and when I ran npm install/update, it blew away my changes.  

From what I can tell, @otaviocx implemented both the function and the tests.

**Comment by DanielRuf** [comment]
> @j-rewerts this is implemented in #599 as of November 2019. Is it possible to please merge that change in and release it. I have been hacking the module manually pasting the changes in

You can use https://github.com/github-tools/github/pull/599.patch and [`patch-package`](https://npmjs.com/patch-package) to apply these changes too.

**Comment by j-rewerts** [comment]
Closing in favour of #599 .

**Pull request closed without merging**
