### PR TITLE
Bump version of Axios

### PR DESCRIPTION
**Pull request by maluramichael**
Right now i get a github warning because the old version of axios has some major security warnings.

### CODE REVIEW

**Comment by kb0rg** [comment]
Hi @j-rewerts, do you have an ETA for resolving this? I'm aware of issue #564 (thank you for outlining all that), but am not prepared to switch to Octokit at the moment. In the meantime, I'm very much looking forward to seeing this patch land. Thank you!

**Comment by j-rewerts** [comment]
Sorry for the delay! Just trying to get the tests to pass.

**Comment by kb0rg** [comment]
Thanks! And... no worries at all, I was mainly curious whether you had a timeframe in mind, so I could use that to weigh whether I should be looking into Octokit more seriously. Thank you!

**Comment by j-rewerts** [comment]
We've got quite a few tests failing for all of our versions, so it could take some time. I'll follow up in ~4 hours after banging my head on it and get a more solid timeline for this.

**Comment by j-rewerts** [comment]
Okay I've got an update on the tests. GitHub has modified their requirements for certain endpoints. Gists now require an account with a confirmed email address, for example. I'll get these tests fixed up and submitted as part of my PR in #567.

**Comment by j-rewerts** [comment]
In the interest of averting security issues, I'll merge this in, and fix the tests after (against my better judgement).

**Pull request merged**
