### PR TITLE
Added option to include license in repository details

### PR DESCRIPTION
**Pull request by synthss**

### CODE REVIEW

**Comment by j-rewerts** [comment]
@synthss Could you add a test for this?

**Comment by synthss** [comment]
sure, i'll try to add a test later and will update you

**Comment by j-rewerts** [comment]
@synthss Any progress on this?

**Comment by synthss** [comment]
Hi @j-rewerts 
I reviewed the tests and the license is already included in `Repository.getDetails` method. Closing this pull request

**Pull request closed without merging**
