### PR TITLE
feat: Issue get/delete/edit/list for labels

### PR DESCRIPTION
**Pull request by vicb**
plus some other minor changes

### CODE REVIEW

**Comment by vicb** [comment]
It seems like the CI is failing on creating a new issue, any idea why ?

**Comment by vicb** [comment]
any plan to get this in ?

**Comment by mathieudutour** [comment]
I'd love to see that merged!

How about `createLabel`? (https://developer.github.com/v3/issues/labels/#create-a-label)

**Comment by lukem512** [comment]
👍 for this

**Comment by vicb** [comment]
Closing as never merged and now conflicting

**Pull request closed without merging**
