### PR TITLE
WIP: Fix linting that is failing the CI

### PR DESCRIPTION
**Pull request by mtscout6**
May I suggest that you migrate this repo to an organization and institute protected branch support on master so PRs cannot be merged when the CI is failing?

See: #263

### CODE REVIEW

**Comment by mtscout6** [comment]
Looks like the mikedeboertest/TestRepo has been deleted which is why a number of the tests are broken. Does anyone know why that repo was deleted?

**Comment by mtscout6** [comment]
I recreated the repo for that test user account

**Comment by mtscout6** [comment]
Ok, I got hit with a 403 rate limited for the mikedeboertest account. So, I'll need to wait for that rate limit to go down before I can try again.

**Comment by mathieudutour** [comment]
I got the tests passing here: https://github.com/mathieudutour/github https://travis-ci.org/mathieudutour/github

**Comment by mtscout6** [comment]
@mathieudutour Instead of pushing yet another fork and another module pushed up to npm I'd much rather see #263 happen and just get more people to work together. @michael What is holding this up from getting more people to help with it? I can so two active forks of this project and I'd really hate to side step the team that originally put this promised based wrapper together.

**Comment by clayreimann** [comment]
@mtscout6 @michael does not actively monitor the notifications from this repo. If we want to move this to an org (probably a good idea) we'll need to reach out to him directly.

**Comment by mathieudutour** [comment]
Indeed, I'd be happy to help.

(I published my fork because I needed some of the opened PRs merged for a project.)

**Comment by clayreimann** [comment]
great, well I'll reach out and see if we can get the repo moved.

**Comment by mtscout6** [comment]
The Issue tests should be fixed now. Still have 10 more failing tests

**Comment by mtscout6** [comment]
Nevermind, something is still deleting that repo...

**Comment by mathieudutour** [comment]
I removed the dependency to that repo in my fork. I'll create a PR soon but there will be lots of changes.

**Comment by mathieudutour** [comment]
see https://github.com/github-tools/github/pull/401

**Comment by mtscout6** [comment]
Closing in favor of #401

**Pull request closed without merging**
