### PR TITLE
Add two new functionality: get files from PR, add comment to PR/issue

### PR DESCRIPTION
**Pull request by haubc**

### CODE REVIEW

**Comment by aendrew** [comment]
Couple of things:
1. This should be part of the Issues API, not Repo API.
2. Please squash commits.
3. Please document the new functionality it README.md
4. Please write unit tests.

Thanks!

**Comment by aendrew** [comment]
Closed in error; reopening.

**Comment by AurelioDeRosa** [comment]
Hi @haubc. Are you still intersted in updating this PR?

**Comment by DanielRuf** [comment]
Closing this as we did not receive any further feedback, there are conflicts and there is already some funcitonality at https://github.com/github-tools/github/blob/11e74f598638ea8fb4af5967a7b56943aa5d1aa9/lib/Repository.js#L118

**Pull request closed without merging**
